name: hi_doc
description: AI-powered chat-based health tracker
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.5+1
  collection: ^1.18.0
  intl: ^0.20.2
  table_calendar: ^3.1.2
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^1.0.1+1
  sqflite_common_ffi: ^2.3.0  # For Linux/Windows/macOS desktop support
  path: ^1.9.0
  path_provider: ^2.1.3
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  flutter_appauth: ^9.0.1 # For Microsoft OAuth (with Azure AD B2C or MS identity)
  http: ^1.2.1
  file_picker: ^10.3.2
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  fl_chart: ^1.1.0
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0  # (unchanged; kept for clarity)
  uuid: ^4.4.0
  timeago: ^3.6.1
  # flutter_secure_storage: ^9.2.4 # temporarily disabled due to Linux compilation issues
  # llama_cpp_dart: ^0.1.0 # earliest available version for local tiny LLaMA inference support (temporarily disabled for Linux desktop compatibility)
  contacts_service: ^0.6.3 # For accessing device contacts
  permission_handler: ^12.0.1 # Upgraded (Stage B)
  image_picker: ^1.1.2 # For camera and gallery access
  flutter_pdfview: ^1.3.2 # For PDF viewing
  pdfx: ^2.9.2 # Updated to match CDN pdf.js version used in index.html
  flutter_html: ^3.0.0-beta.2 # For rendering HTML content in AI responses

  # Optional (choose one chart lib); syncfusion requires license key for prod
  # syncfusion_flutter_charts: ^26.1.41

  # AI parsing abstraction (implement later / plugin pattern)
  # openai_api: ^<placeholder>

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.0
  mocktail: ^1.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/reports/
    - assets/prescriptions/
    - assets/models/
    - assets/prompts/
    - assets/images/hi-doc.png

flutter_launcher_icons:
  image_path: assets/images/hi-doc.png
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/hi-doc.png
  web:
    generate: true
    image_path: assets/images/hi-doc.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: assets/images/hi-doc.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/images/hi-doc.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/hi-doc.png
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/images/hi-doc.png
    icon_background_color: "#FFFFFF"
  web: true
