-- Enable foreign key support
PRAGMA foreign_keys = ON;

-- Create users table if not exists
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  photo_url TEXT,
  phone TEXT,
  is_external INTEGER DEFAULT 0
);

-- Create profiles table (renamed from conversations)
CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY,
  title TEXT,
  type TEXT NOT NULL DEFAULT 'direct',
  is_default INTEGER DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

-- Create profile_members table (renamed from conversation_members)
CREATE TABLE IF NOT EXISTS profile_members (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  is_admin INTEGER DEFAULT 0,
  joined_at INTEGER NOT NULL,
  last_read_at INTEGER NOT NULL,
  FOREIGN KEY(profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create messages table with profile support (conversation renamed to profile)
CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  sender_id TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  content TEXT NOT NULL,
  content_type TEXT DEFAULT 'text',
  created_at INTEGER NOT NULL,
  interpretation_json TEXT,
  processed INTEGER DEFAULT 0,
  stored_record_id TEXT,
  FOREIGN KEY(profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create all other tables with profile_id (except param_targets)
CREATE TABLE IF NOT EXISTS health_data (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  profile_id TEXT NOT NULL,
  type TEXT NOT NULL,
  category TEXT DEFAULT 'HEALTH_PARAMS',
  value TEXT,
  quantity TEXT,
  unit TEXT,
  timestamp INTEGER NOT NULL,
  notes TEXT,
  report_id TEXT, -- optional link to the report it came from
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

-- Normalized Medications Schema
-- 1) medications: base drug record per user+profile
CREATE TABLE IF NOT EXISTS medications (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  profile_id TEXT NOT NULL,
  name TEXT NOT NULL,
  notes TEXT,
  medication_url TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

-- 2) medication_schedules: recurrence window & configuration
CREATE TABLE IF NOT EXISTS medication_schedules (
  id TEXT PRIMARY KEY,
  medication_id TEXT NOT NULL,
  schedule TEXT NOT NULL,              -- human-readable frequency descriptor
  frequency_per_day INTEGER,           -- optional; e.g. 2
  is_forever INTEGER DEFAULT 0,        -- 1=indefinite
  start_date INTEGER,                  -- epoch ms
  end_date INTEGER,                    -- nullable if is_forever=1
  days_of_week TEXT,                   -- CSV of MON,TUE,... or 0-6
  timezone TEXT,                       -- IANA TZ
  reminder_enabled INTEGER DEFAULT 1,  -- 1=on
  FOREIGN KEY(medication_id) REFERENCES medications(id) ON DELETE CASCADE
);

-- 3) medication_schedule_times: specific dose times & dosage meta
CREATE TABLE IF NOT EXISTS medication_schedule_times (
  id TEXT PRIMARY KEY,
  schedule_id TEXT NOT NULL,
  time_local TEXT NOT NULL,            -- HH:MM 24h in schedule timezone
  dosage TEXT,                         -- free text: "1 tab (500 mg)"
  dose_amount REAL,
  dose_unit TEXT,
  instructions TEXT,                   -- e.g., before breakfast
  prn INTEGER DEFAULT 0,               -- 1=as needed
  sort_order INTEGER,
  next_trigger_ts INTEGER,             -- cached next notification time
  FOREIGN KEY(schedule_id) REFERENCES medication_schedules(id) ON DELETE CASCADE
);

-- 4) medication_intake_logs: adherence tracking
CREATE TABLE IF NOT EXISTS medication_intake_logs (
  id TEXT PRIMARY KEY,
  schedule_time_id TEXT NOT NULL,
  taken_ts INTEGER NOT NULL,
  status TEXT NOT NULL,                -- taken|missed|skipped|snoozed
  actual_dose_amount REAL,
  actual_dose_unit TEXT,
  notes TEXT,
  FOREIGN KEY(schedule_time_id) REFERENCES medication_schedule_times(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reports (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  profile_id TEXT, -- nullable, if report came from a profile
  file_path TEXT NOT NULL, -- local path to scanned image or PDF
  file_type TEXT NOT NULL, -- e.g. 'pdf', 'image'
  source TEXT NOT NULL, -- 'camera', 'upload', 'profile'
  ai_summary TEXT, -- summary generated by AI agent
  created_at INTEGER NOT NULL,
  parsed INTEGER DEFAULT 0, -- 0 = not parsed, 1 = parsed
  original_file_name TEXT, -- original uploaded filename
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(profile_id) REFERENCES profiles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS reminders (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  profile_id TEXT NOT NULL,
  medication_id TEXT,
  title TEXT NOT NULL,
  time TEXT NOT NULL,
  message TEXT,
  repeat TEXT,
  days TEXT,
  active INTEGER DEFAULT 1,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  FOREIGN KEY(medication_id) REFERENCES medications(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS activities (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  profile_id TEXT NOT NULL,
  name TEXT NOT NULL,
  duration_minutes INTEGER,
  distance_km REAL,
  intensity TEXT,
  calories_burned REAL,
  timestamp INTEGER NOT NULL,
  notes TEXT,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

-- Create param_targets table (no profile_id needed as requested)
CREATE TABLE IF NOT EXISTS param_targets (
  param_code TEXT PRIMARY KEY,
  target_min REAL,
  target_max REAL,
  preferred_unit TEXT,
  description TEXT,
  notes TEXT,
  organ_system TEXT
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_health_data_user_ts ON health_data(user_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_health_data_category ON health_data(category);
CREATE INDEX IF NOT EXISTS idx_health_data_profile ON health_data(profile_id);
CREATE INDEX IF NOT EXISTS idx_medications_user ON medications(user_id);
CREATE INDEX IF NOT EXISTS idx_medications_profile ON medications(profile_id);
CREATE INDEX IF NOT EXISTS idx_medications_name ON medications(name);
CREATE INDEX IF NOT EXISTS idx_schedules_medication ON medication_schedules(medication_id);
CREATE INDEX IF NOT EXISTS idx_schedules_active_window ON medication_schedules(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_times_schedule ON medication_schedule_times(schedule_id);
CREATE INDEX IF NOT EXISTS idx_times_trigger ON medication_schedule_times(next_trigger_ts);
CREATE INDEX IF NOT EXISTS idx_intake_logs_time ON medication_intake_logs(taken_ts);
CREATE INDEX IF NOT EXISTS idx_reports_user ON reports(user_id);
CREATE INDEX IF NOT EXISTS idx_reports_profile ON reports(profile_id);
CREATE INDEX IF NOT EXISTS idx_reminders_user ON reminders(user_id);
CREATE INDEX IF NOT EXISTS idx_reminders_profile ON reminders(profile_id);
CREATE INDEX IF NOT EXISTS idx_activities_user ON activities(user_id);
CREATE INDEX IF NOT EXISTS idx_activities_profile ON activities(profile_id);
CREATE INDEX IF NOT EXISTS idx_profile_members_user ON profile_members(user_id);
CREATE INDEX IF NOT EXISTS idx_profile_members_convo ON profile_members(profile_id);
CREATE INDEX IF NOT EXISTS idx_messages_profile_time ON messages(profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);

-- Insert seed data
-- Create default user for development
INSERT OR IGNORE INTO users (id, name, email) 
VALUES ('prototype-user-12345', 'Dev User', 'dev@example.com');

-- Add some sample users for testing search functionality
INSERT OR IGNORE INTO users (id, name, email, photo_url) VALUES 
  ('user-001', 'Alice Johnson', 'alice.johnson@example.com', NULL),
  ('user-002', 'Bob Smith', 'bob.smith@example.com', NULL),
  ('user-003', 'Carol Davis', 'carol.davis@example.com', NULL),
  ('user-004', 'David Wilson', 'david.wilson@example.com', NULL),
  ('user-005', 'Emma Brown', 'emma.brown@example.com', NULL),
  ('user-006', 'Frank Miller', 'frank.miller@example.com', NULL),
  ('user-007', 'Grace Lee', 'grace.lee@example.com', NULL),
  ('user-008', 'Henry Taylor', 'henry.taylor@example.com', NULL),
  ('user-009', 'Ivy Chen', 'ivy.chen@example.com', NULL),
  ('user-010', 'Jack Roberts', 'jack.roberts@example.com', NULL);

-- Create default profile
INSERT OR IGNORE INTO profiles (
  id,
  title,
  type,
  is_default,
  created_at,
  updated_at
) VALUES (
  'default-profile',
  'Me',
  'direct',
  1,
  strftime('%s', 'now') * 1000,
  strftime('%s', 'now') * 1000
);

-- Add dev user to default profile
INSERT OR IGNORE INTO profile_members (
  id,
  profile_id,
  user_id,
  is_admin,
  joined_at,
  last_read_at
) VALUES (
  'member_default_prototype-user-12345',
  'default-profile',
  'prototype-user-12345',
  1,
  strftime('%s', 'now') * 1000,
  strftime('%s', 'now') * 1000
);
